# Generated by Django 5.2 on 2025-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('I', 'In progress'), ('D', 'Done')], default='I', max_length=1)),
                ('priority', models.CharField(choices=[('U', 'Виконати Терміново / Complete urgently'), ('NU', 'Виконання не є терміновим  / Completion is not urgent')], default='NU', max_length=2)),
            ],
        ),
    ]
