# Generated by Django 5.2 on 2025-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('I', 'In progress'), ('D', 'Done'), ('F', 'Faild')], default='I', max_length=1),
        ),
    ]
